package com.financial.connector.entity;

import com.financial.connector.model.EligibilityStatus;
import com.financial.connector.model.IncomeSource;
import com.financial.connector.model.LoanType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "foir_assessments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FoirAssessment {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Auth-service user UUID. Stored as a plain column — cross-schema FK not used. */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "loan_type", nullable = false, length = 50)
    private LoanType loanType;

    @Column(name = "gross_monthly_income", nullable = false, precision = 15, scale = 2)
    private BigDecimal grossMonthlyIncome;

    @Column(name = "existing_monthly_obligations", nullable = false, precision = 15, scale = 2)
    private BigDecimal existingMonthlyObligations;

    @Column(name = "requested_loan_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal requestedLoanAmount;

    @Column(name = "requested_tenure_months", nullable = false)
    private int requestedTenureMonths;

    @Column(name = "annual_interest_rate", nullable = false, precision = 5, scale = 2)
    private BigDecimal annualInterestRate;

    /** Pre-loan FOIR: existingObligations / grossIncome × 100. */
    @Column(name = "calculated_foir_percentage", nullable = false, precision = 5, scale = 2)
    private BigDecimal calculatedFoirPercentage;

    @Column(name = "max_eligible_emi", nullable = false, precision = 15, scale = 2)
    private BigDecimal maxEligibleEmi;

    @Column(name = "max_eligible_loan_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal maxEligibleLoanAmount;

    /** Post-loan FOIR: (existingObligations + proposedEmi) / grossIncome × 100. */
    @Column(name = "post_loan_foir_percentage", nullable = false, precision = 5, scale = 2)
    private BigDecimal postLoanFoirPercentage;

    @Enumerated(EnumType.STRING)
    @Column(name = "eligibility_status", nullable = false, length = 20)
    private EligibilityStatus eligibilityStatus;

    /** The FOIR limit (%) that was in effect at the time of this assessment. */
    @Column(name = "foir_limit_applied", nullable = false, precision = 5, scale = 2)
    private BigDecimal foirLimitApplied;

    @Enumerated(EnumType.STRING)
    @Column(name = "income_source", nullable = false, length = 50)
    private IncomeSource incomeSource;

    /** Human-readable eligibility verdict generated by FoirCalculationEngine. */
    @Column(name = "assessment_notes", columnDefinition = "TEXT")
    private String assessmentNotes;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
