// Comprehensive India location data — all states/UTs, major districts, and cities
// where banks and NBFCs operate. "Others" is always available as the last city option.
export const INDIA_LOCATIONS: Record<string, Record<string, string[]>> = {
  'Andhra Pradesh': {
    'Anantapur': ['Anantapur', 'Guntakal', 'Hindupur', 'Kadiri', 'Dharmavaram', 'Tadipatri', 'Others'],
    'Chittoor': ['Tirupati', 'Chittoor', 'Madanapalle', 'Kuppam', 'Punganur', 'Others'],
    'East Godavari': ['Rajahmundry', 'Kakinada', 'Amalapuram', 'Samalkot', 'Peddapuram', 'Ramachandrapuram', 'Others'],
    'Guntur': ['Guntur', 'Tenali', 'Narasaraopet', 'Bapatla', 'Mangalagiri', 'Ponnur', 'Macherla', 'Others'],
    'Krishna': ['Vijayawada', 'Machilipatnam', 'Gudivada', 'Nuzvid', 'Nandigama', 'Others'],
    'Kurnool': ['Kurnool', 'Nandyal', 'Adoni', 'Yemmiganur', 'Dhone', 'Others'],
    'Nellore': ['Nellore', 'Kavali', 'Gudur', 'Atmakur', 'Sullurpeta', 'Others'],
    'Prakasam': ['Ongole', 'Markapur', 'Chirala', 'Kandukur', 'Giddalur', 'Others'],
    'Srikakulam': ['Srikakulam', 'Amadalavalasa', 'Narasannapeta', 'Palasa', 'Others'],
    'Visakhapatnam': ['Visakhapatnam', 'Gajuwaka', 'Bheemunipatnam', 'Anakapalle', 'Narsipatnam', 'Others'],
    'Vizianagaram': ['Vizianagaram', 'Bobbili', 'Gajapathinagaram', 'Salur', 'Others'],
    'West Godavari': ['Eluru', 'Bhimavaram', 'Tanuku', 'Palakol', 'Tadepalligudem', 'Narsapur', 'Others'],
    'YSR Kadapa': ['Kadapa', 'Proddatur', 'Rajampet', 'Pulivendla', 'Jammalamadugu', 'Others'],
  },
  'Arunachal Pradesh': {
    'Itanagar Capital Region': ['Itanagar', 'Naharlagun', 'Nirjuli', 'Others'],
    'East Siang': ['Pasighat', 'Mebo', 'Others'],
    'West Siang': ['Aalo', 'Ziro', 'Others'],
    'Tawang': ['Tawang', 'Others'],
    'Papum Pare': ['Yupia', 'Banderdewa', 'Others'],
    'Changlang': ['Changlang', 'Nampong', 'Others'],
  },
  'Assam': {
    'Kamrup Metropolitan': ['Guwahati', 'Dispur', 'Beltola', 'Chandmari', 'Jalukbari', 'Azara', 'Others'],
    'Kamrup': ['Boko', 'Hajo', 'Mirza', 'Palashbari', 'Rangia', 'Others'],
    'Dibrugarh': ['Dibrugarh', 'Naharkatia', 'Duliajan', 'Moran', 'Lahowal', 'Others'],
    'Jorhat': ['Jorhat', 'Mariani', 'Titabor', 'Others'],
    'Sonitpur': ['Tezpur', 'Rangapara', 'Dhekiajuli', 'Biswanath', 'Others'],
    'Nagaon': ['Nagaon', 'Hojai', 'Lumding', 'Doboka', 'Others'],
    'Cachar': ['Silchar', 'Sonai', 'Udharbond', 'Others'],
    'Lakhimpur': ['North Lakhimpur', 'Dhakuakhana', 'Narayanpur', 'Others'],
    'Bongaigaon': ['Bongaigaon', 'Bijni', 'Sidli', 'Others'],
    'Barpeta': ['Barpeta', 'Pathsala', 'Sorbhog', 'Baghbar', 'Others'],
    'Darrang': ['Mangaldai', 'Sipajhar', 'Others'],
    'Golaghat': ['Golaghat', 'Numaligarh', 'Sarupathar', 'Others'],
    'Sivasagar': ['Sivasagar', 'Nazira', 'Sonari', 'Others'],
    'Tinsukia': ['Tinsukia', 'Doom Dooma', 'Digboi', 'Others'],
    'Karbi Anglong': ['Diphu', 'Bokajan', 'Others'],
    'Dhubri': ['Dhubri', 'Bilasipara', 'Gauripur', 'Others'],
    'Kokrajhar': ['Kokrajhar', 'Gossaigaon', 'Others'],
    'Nalbari': ['Nalbari', 'Tihu', 'Ghograpar', 'Others'],
    'Morigaon': ['Morigaon', 'Jagiroad', 'Others'],
    'Hailakandi': ['Hailakandi', 'Lala', 'Others'],
  },
  'Bihar': {
    'Patna': ['Patna', 'Danapur', 'Phulwarisharif', 'Khagaul', 'Barh', 'Fatuha', 'Bikram', 'Maner', 'Others'],
    'Gaya': ['Gaya', 'Bodh Gaya', 'Sherghati', 'Tekari', 'Dobhi', 'Others'],
    'Bhagalpur': ['Bhagalpur', 'Sultanganj', 'Naugachia', 'Others'],
    'Muzaffarpur': ['Muzaffarpur', 'Sitamarhi', 'Motihari', 'Bettiah', 'Raxaul', 'Others'],
    'Darbhanga': ['Darbhanga', 'Madhubani', 'Biraul', 'Others'],
    'Samastipur': ['Samastipur', 'Rosera', 'Dalsinghsarai', 'Others'],
    'Purnia': ['Purnia', 'Katihar', 'Araria', 'Kishanganj', 'Others'],
    'Begusarai': ['Begusarai', 'Barauni', 'Others'],
    'Siwan': ['Siwan', 'Gopalganj', 'Others'],
    'Bhojpur': ['Ara', 'Jagdishpur', 'Bihiya', 'Others'],
    'Rohtas': ['Sasaram', 'Dehri', 'Bhabua', 'Others'],
    'Buxar': ['Buxar', 'Dumraon', 'Others'],
    'Munger': ['Munger', 'Lakhisarai', 'Sheikhpura', 'Jamalpur', 'Others'],
    'Nalanda': ['Biharsharif', 'Rajgir', 'Hilsa', 'Others'],
    'Saran': ['Chapra', 'Marhaura', 'Revelganj', 'Others'],
    'Vaishali': ['Hajipur', 'Lalganj', 'Others'],
    'Champaran East': ['Motihari', 'Raxaul', 'Others'],
    'Champaran West': ['Bettiah', 'Narkatiaganj', 'Others'],
    'Jehanabad': ['Jehanabad', 'Makhdumpur', 'Others'],
    'Aurangabad': ['Aurangabad', 'Daudnagar', 'Others'],
    'Nawada': ['Nawada', 'Rajauli', 'Others'],
    'Khagaria': ['Khagaria', 'Mansi', 'Others'],
    'Supaul': ['Supaul', 'Triveniganj', 'Others'],
    'Madhepura': ['Madhepura', 'Murliganj', 'Others'],
    'Madhubani': ['Madhubani', 'Jaynagar', 'Others'],
    'Sitamarhi': ['Sitamarhi', 'Sheohar', 'Others'],
    'Sheohar': ['Sheohar', 'Others'],
    'Jamui': ['Jamui', 'Jhajha', 'Others'],
    'Banka': ['Banka', 'Amarpur', 'Others'],
    'Arwal': ['Arwal', 'Others'],
  },
  'Chhattisgarh': {
    'Raipur': ['Raipur', 'Naya Raipur', 'Arang', 'Abhanpur', 'Others'],
    'Durg': ['Durg', 'Bhilai', 'Rajnandgaon', 'Balod', 'Others'],
    'Bilaspur': ['Bilaspur', 'Korba', 'Raigarh', 'Katghora', 'Others'],
    'Korba': ['Korba', 'Katghora', 'Champa', 'Others'],
    'Jagdalpur': ['Jagdalpur', 'Kondagaon', 'Narayanpur', 'Others'],
    'Ambikapur': ['Ambikapur', 'Surajpur', 'Balrampur', 'Others'],
    'Raigarh': ['Raigarh', 'Sarangarh', 'Gharghoda', 'Others'],
    'Rajnandgaon': ['Rajnandgaon', 'Dongargarh', 'Others'],
    'Mahasamund': ['Mahasamund', 'Pithaura', 'Others'],
    'Dhamtari': ['Dhamtari', 'Kurud', 'Others'],
    'Janjgir-Champa': ['Janjgir', 'Champa', 'Akaltara', 'Others'],
    'Kabirdham': ['Kawardha', 'Pandariya', 'Others'],
    'Kanker': ['Kanker', 'Charama', 'Others'],
    'Sukma': ['Sukma', 'Others'],
    'Bijapur': ['Bijapur', 'Bhopalpatnam', 'Others'],
    'Mungeli': ['Mungeli', 'Lormi', 'Others'],
    'Gariaband': ['Gariaband', 'Mainpur', 'Others'],
  },
  'Goa': {
    'North Goa': ['Panaji', 'Mapusa', 'Ponda', 'Calangute', 'Candolim', 'Pernem', 'Bicholim', 'Others'],
    'South Goa': ['Margao', 'Vasco da Gama', 'Verna', 'Cuncolim', 'Sanguem', 'Quepem', 'Canacona', 'Others'],
  },
  'Gujarat': {
    'Ahmedabad': ['Ahmedabad', 'Gandhinagar', 'Narol', 'Vatva', 'Maninagar', 'Bopal', 'Gota', 'Naroda', 'Chandkheda', 'Odhav', 'Nikol', 'Others'],
    'Surat': ['Surat', 'Bardoli', 'Navsari', 'Kim', 'Vyara', 'Olpad', 'Mandvi', 'Others'],
    'Vadodara': ['Vadodara', 'Anand', 'Karjan', 'Halol', 'Padra', 'Savli', 'Others'],
    'Rajkot': ['Rajkot', 'Gondal', 'Morbi', 'Jetpur', 'Wankaner', 'Upleta', 'Others'],
    'Bhavnagar': ['Bhavnagar', 'Sihor', 'Palitana', 'Mahuva', 'Talaja', 'Others'],
    'Jamnagar': ['Jamnagar', 'Dwarka', 'Khambhalia', 'Lalpur', 'Others'],
    'Junagadh': ['Junagadh', 'Somnath', 'Veraval', 'Keshod', 'Porbandar', 'Others'],
    'Mehsana': ['Mehsana', 'Unjha', 'Visnagar', 'Patan', 'Kheralu', 'Others'],
    'Gandhinagar': ['Gandhinagar', 'Kalol', 'Mansa', 'Dehgam', 'Others'],
    'Amreli': ['Amreli', 'Rajula', 'Savarkundla', 'Lathi', 'Others'],
    'Anand': ['Anand', 'Vallabh Vidyanagar', 'Nadiad', 'Petlad', 'Khambhat', 'Others'],
    'Bharuch': ['Bharuch', 'Ankleshwar', 'Jambusar', 'Hansot', 'Others'],
    'Kheda': ['Kheda', 'Nadiad', 'Kapadvanj', 'Mahemdabad', 'Others'],
    'Panchmahal': ['Godhra', 'Halol', 'Lunawada', 'Kalol', 'Others'],
    'Dahod': ['Dahod', 'Limkheda', 'Devgadh Baria', 'Others'],
    'Surendranagar': ['Surendranagar', 'Wadhwan', 'Dhrangadhra', 'Halvad', 'Others'],
    'Tapi': ['Vyara', 'Songadh', 'Uchchhal', 'Others'],
    'Valsad': ['Valsad', 'Vapi', 'Bilimora', 'Umbergaon', 'Others'],
    'Narmada': ['Rajpipla', 'Dediapada', 'Others'],
    'Kutch': ['Bhuj', 'Gandhidham', 'Anjar', 'Mundra', 'Mandvi', 'Others'],
    'Porbandar': ['Porbandar', 'Ranavav', 'Others'],
    'Gir Somnath': ['Veraval', 'Somnath', 'Una', 'Others'],
    'Botad': ['Botad', 'Barwala', 'Others'],
    'Aravalli': ['Modasa', 'Malpur', 'Bayad', 'Others'],
    'Mahisagar': ['Lunawada', 'Santrampur', 'Others'],
    'Chhota Udaipur': ['Chhota Udaipur', 'Kavant', 'Others'],
    'Devbhoomi Dwarka': ['Dwarka', 'Okha', 'Others'],
    'Morbi': ['Morbi', 'Wankaner', 'Tankara', 'Others'],
  },
  'Haryana': {
    'Gurugram': ['Gurugram', 'Sohna', 'Manesar', 'Pataudi', 'Farrukhnagar', 'Others'],
    'Faridabad': ['Faridabad', 'Ballabhgarh', 'Palwal', 'Hodal', 'Others'],
    'Ambala': ['Ambala', 'Ambala Cantt', 'Shahabad', 'Naraingarh', 'Barara', 'Others'],
    'Hisar': ['Hisar', 'Hansi', 'Fatehabad', 'Sirsa', 'Barwala', 'Others'],
    'Rohtak': ['Rohtak', 'Jhajjar', 'Bahadurgarh', 'Maham', 'Others'],
    'Karnal': ['Karnal', 'Panipat', 'Kaithal', 'Kurukshetra', 'Gharaunda', 'Assandh', 'Others'],
    'Sonipat': ['Sonipat', 'Gohana', 'Kundli', 'Gannaur', 'Kharkhoda', 'Others'],
    'Yamunanagar': ['Yamunanagar', 'Jagadhri', 'Chhachhrauli', 'Others'],
    'Bhiwani': ['Bhiwani', 'Charkhi Dadri', 'Loharu', 'Others'],
    'Rewari': ['Rewari', 'Dharuhera', 'Bawal', 'Kosli', 'Others'],
    'Panchkula': ['Panchkula', 'Kalka', 'Pinjore', 'Morni', 'Others'],
    'Mahendragarh': ['Narnaul', 'Mahendragarh', 'Nangal Chaudhary', 'Others'],
    'Nuh': ['Nuh', 'Ferozepur Jhirka', 'Tauru', 'Others'],
    'Fatehabad': ['Fatehabad', 'Tohana', 'Ratia', 'Others'],
    'Jind': ['Jind', 'Safidon', 'Narwana', 'Uchana', 'Others'],
    'Kurukshetra': ['Kurukshetra', 'Thanesar', 'Shahabad', 'Others'],
    'Panipat': ['Panipat', 'Samalkha', 'Israna', 'Others'],
    'Kaithal': ['Kaithal', 'Pundri', 'Cheeka', 'Others'],
    'Palwal': ['Palwal', 'Hodal', 'Hathin', 'Others'],
    'Sirsa': ['Sirsa', 'Dabwali', 'Rania', 'Others'],
  },
  'Himachal Pradesh': {
    'Shimla': ['Shimla', 'Solan', 'Parwanoo', 'Baddi', 'Nalagarh', 'Kasauli', 'Others'],
    'Kangra': ['Dharamsala', 'Palampur', 'Hamirpur', 'Nurpur', 'Dehra Gopipur', 'Others'],
    'Mandi': ['Mandi', 'Sundarnagar', 'Jogindernagar', 'Others'],
    'Una': ['Una', 'Bangana', 'Haroli', 'Others'],
    'Kullu': ['Kullu', 'Manali', 'Bhuntar', 'Anni', 'Others'],
    'Bilaspur': ['Bilaspur', 'Ghumarwin', 'Others'],
    'Chamba': ['Chamba', 'Dalhousie', 'Bharmour', 'Others'],
    'Sirmaur': ['Nahan', 'Paonta Sahib', 'Rajgarh', 'Others'],
    'Kinnaur': ['Reckong Peo', 'Sangla', 'Others'],
    'Lahaul and Spiti': ['Keylong', 'Kaza', 'Others'],
    'Solan': ['Solan', 'Baddi', 'Parwanoo', 'Nalagarh', 'Kasauli', 'Others'],
    'Hamirpur': ['Hamirpur', 'Sujanpur', 'Barsar', 'Others'],
  },
  'Jharkhand': {
    'Ranchi': ['Ranchi', 'Hatia', 'Kanke', 'Namkum', 'Tamar', 'Bundu', 'Others'],
    'Jamshedpur': ['Jamshedpur', 'Jugsalai', 'Mango', 'Adityapur', 'Gamharia', 'Others'],
    'Dhanbad': ['Dhanbad', 'Jharia', 'Sindri', 'Chas', 'Others'],
    'Bokaro': ['Bokaro Steel City', 'Chas', 'Bermo', 'Others'],
    'Hazaribag': ['Hazaribag', 'Ramgarh', 'Chatra', 'Barhi', 'Others'],
    'Deoghar': ['Deoghar', 'Jasidih', 'Madhupur', 'Others'],
    'Giridih': ['Giridih', 'Dhanbad', 'Bagodar', 'Others'],
    'Dumka': ['Dumka', 'Pakur', 'Shikaripara', 'Others'],
    'Palamu': ['Daltonganj', 'Medininagar', 'Hussainabad', 'Others'],
    'Gumla': ['Gumla', 'Simdega', 'Others'],
    'Lohardaga': ['Lohardaga', 'Bishunpur', 'Others'],
    'Sahebganj': ['Sahebganj', 'Rajmahal', 'Others'],
    'Godda': ['Godda', 'Mahagama', 'Others'],
    'Jamtara': ['Jamtara', 'Nala', 'Others'],
    'Seraikela-Kharsawan': ['Seraikela', 'Kharsawan', 'Others'],
    'West Singhbhum': ['Chaibasa', 'Chakradharpur', 'Others'],
    'East Singhbhum': ['Jamshedpur', 'Baharagora', 'Others'],
    'Khunti': ['Khunti', 'Murhu', 'Others'],
    'Simdega': ['Simdega', 'Kurdeg', 'Others'],
  },
  'Karnataka': {
    'Bangalore Urban': ['Bengaluru', 'Whitefield', 'Electronic City', 'Koramangala', 'Indiranagar', 'Jayanagar', 'Malleshwaram', 'Rajajinagar', 'Hebbal', 'Yelahanka', 'Marathahalli', 'Sarjapur Road', 'JP Nagar', 'Bannerghatta Road', 'Others'],
    'Bangalore Rural': ['Devanahalli', 'Doddaballapur', 'Hoskote', 'Nelamangala', 'Others'],
    'Mysore': ['Mysore', 'Hunsur', 'Mandya', 'Srirangapatna', 'Nanjangud', 'Others'],
    'Dharwad': ['Hubli', 'Dharwad', 'Kundgol', 'Others'],
    'Dakshina Kannada': ['Mangalore', 'Puttur', 'Sullia', 'Bantwal', 'Others'],
    'Udupi': ['Udupi', 'Manipal', 'Karkala', 'Brahmavar', 'Others'],
    'Belagavi': ['Belagavi', 'Belgaum', 'Nipani', 'Gokak', 'Bailhongal', 'Others'],
    'Kalaburagi': ['Kalaburagi', 'Gulbarga', 'Sedam', 'Chincholi', 'Others'],
    'Bidar': ['Bidar', 'Bhalki', 'Humnabad', 'Others'],
    'Raichur': ['Raichur', 'Manvi', 'Lingsugur', 'Others'],
    'Tumakuru': ['Tumakuru', 'Tiptur', 'Chikkanayakanahalli', 'Madhugiri', 'Others'],
    'Shivamogga': ['Shivamogga', 'Bhadravathi', 'Sagar', 'Shimoga', 'Others'],
    'Davangere': ['Davangere', 'Harihar', 'Harapanahalli', 'Channagiri', 'Others'],
    'Ballari': ['Ballari', 'Hospet', 'Sandur', 'Kudligi', 'Others'],
    'Vijayapura': ['Vijayapura', 'Bijapur', 'Muddebihal', 'Indi', 'Others'],
    'Bagalkote': ['Bagalkote', 'Jamkhandi', 'Rabkavi Banhatti', 'Others'],
    'Chitradurga': ['Chitradurga', 'Hiriyur', 'Challakere', 'Others'],
    'Kolar': ['Kolar', 'KGF', 'Malur', 'Mulbagal', 'Others'],
    'Mandya': ['Mandya', 'Maddur', 'Nagamangala', 'Others'],
    'Hassan': ['Hassan', 'Sakleshpur', 'Belur', 'Arsikere', 'Others'],
    'Chikmagalur': ['Chikmagalur', 'Kadur', 'Tarikere', 'Others'],
    'Kodagu': ['Madikeri', 'Somwarpet', 'Virajpet', 'Kushalnagar', 'Others'],
    'Chamarajanagar': ['Chamarajanagar', 'Gundlupet', 'Kollegal', 'Others'],
    'Gadag': ['Gadag', 'Ron', 'Mundaragi', 'Others'],
    'Haveri': ['Haveri', 'Savanur', 'Byadgi', 'Ranibennur', 'Others'],
    'Koppal': ['Koppal', 'Gangavathi', 'Kushtagi', 'Others'],
    'Yadgir': ['Yadgir', 'Shorapur', 'Surpur', 'Others'],
    'Chikkaballapur': ['Chikkaballapur', 'Chintamani', 'Sidlaghatta', 'Others'],
    'Ramanagara': ['Ramanagara', 'Channapatna', 'Magadi', 'Others'],
    'Uttara Kannada': ['Karwar', 'Sirsi', 'Kumta', 'Bhatkal', 'Others'],
  },
  'Kerala': {
    'Thiruvananthapuram': ['Thiruvananthapuram', 'Attingal', 'Nedumangad', 'Varkala', 'Kazhakuttam', 'Peroorkada', 'Others'],
    'Ernakulam': ['Ernakulam', 'Kochi', 'Aluva', 'Angamaly', 'Perumbavoor', 'Muvattupuzha', 'Tripunithura', 'Kakkanad', 'Others'],
    'Kozhikode': ['Kozhikode', 'Vadakara', 'Koyilandy', 'Feroke', 'Ramanattukara', 'Others'],
    'Thrissur': ['Thrissur', 'Guruvayur', 'Kunnamkulam', 'Irinjalakuda', 'Chalakudy', 'Others'],
    'Palakkad': ['Palakkad', 'Ottappalam', 'Chittur', 'Shoranur', 'Mannarkkad', 'Others'],
    'Malappuram': ['Malappuram', 'Tirur', 'Manjeri', 'Perinthalmanna', 'Kondotty', 'Kottakkal', 'Others'],
    'Kollam': ['Kollam', 'Punalur', 'Karunagappally', 'Paravur', 'Others'],
    'Kottayam': ['Kottayam', 'Pala', 'Changanacherry', 'Ettumanoor', 'Kanjirappally', 'Others'],
    'Kannur': ['Kannur', 'Thalassery', 'Payyannur', 'Iritty', 'Others'],
    'Kasaragod': ['Kasaragod', 'Kanhangad', 'Hosdurg', 'Others'],
    'Pathanamthitta': ['Pathanamthitta', 'Thiruvalla', 'Adoor', 'Ranni', 'Others'],
    'Alappuzha': ['Alappuzha', 'Cherthala', 'Kayamkulam', 'Haripad', 'Others'],
    'Idukki': ['Idukki', 'Thodupuzha', 'Munnar', 'Kothamangalam', 'Others'],
    'Wayanad': ['Kalpetta', 'Mananthavady', 'Sulthan Bathery', 'Vythiri', 'Others'],
  },
  'Madhya Pradesh': {
    'Bhopal': ['Bhopal', 'Berasia', 'Sehore', 'Vidisha', 'Others'],
    'Indore': ['Indore', 'Dewas', 'Pithampur', 'Sanwer', 'Mhow', 'Others'],
    'Jabalpur': ['Jabalpur', 'Katni', 'Seoni', 'Chhindwara', 'Narsinghpur', 'Others'],
    'Gwalior': ['Gwalior', 'Morena', 'Bhind', 'Datia', 'Shivpuri', 'Others'],
    'Ujjain': ['Ujjain', 'Nagda', 'Khachrod', 'Badnagar', 'Maksi', 'Others'],
    'Sagar': ['Sagar', 'Damoh', 'Banda', 'Rehli', 'Others'],
    'Rewa': ['Rewa', 'Satna', 'Sidhi', 'Singrauli', 'Others'],
    'Ratlam': ['Ratlam', 'Mandsaur', 'Neemuch', 'Jaora', 'Others'],
    'Hoshangabad': ['Hoshangabad', 'Itarsi', 'Pipariya', 'Sohagpur', 'Others'],
    'Chhindwara': ['Chhindwara', 'Sausar', 'Amarwara', 'Others'],
    'Satna': ['Satna', 'Maihar', 'Nagod', 'Others'],
    'Khandwa': ['Khandwa', 'Harda', 'Punasa', 'Others'],
    'Khargone': ['Khargone', 'Barwani', 'Bhikangaon', 'Others'],
    'Dhar': ['Dhar', 'Mhow', 'Pithampur', 'Kukshi', 'Others'],
    'Balaghat': ['Balaghat', 'Lalbarra', 'Kirnapur', 'Others'],
    'Betul': ['Betul', 'Multai', 'Amla', 'Others'],
    'Burhanpur': ['Burhanpur', 'Nepanagar', 'Others'],
    'Shajapur': ['Shajapur', 'Shujalpur', 'Agar', 'Others'],
    'Vidisha': ['Vidisha', 'Ganj Basoda', 'Gyaraspur', 'Others'],
    'Raisen': ['Raisen', 'Sanchi', 'Obedullaganj', 'Others'],
    'Tikamgarh': ['Tikamgarh', 'Orchha', 'Niwari', 'Others'],
    'Chhatarpur': ['Chhatarpur', 'Khajuraho', 'Nowgong', 'Others'],
    'Panna': ['Panna', 'Pawai', 'Ajaygarh', 'Others'],
    'Damoh': ['Damoh', 'Patera', 'Jabera', 'Others'],
    'Shivpuri': ['Shivpuri', 'Pichhore', 'Kolaras', 'Others'],
    'Guna': ['Guna', 'Mungaoli', 'Raghogarh', 'Others'],
    'Ashoknagar': ['Ashoknagar', 'Chanderi', 'Others'],
    'Narsimhapur': ['Narsimhapur', 'Gadarwara', 'Gotegaon', 'Others'],
    'Mandla': ['Mandla', 'Nainpur', 'Others'],
    'Shahdol': ['Shahdol', 'Umaria', 'Anuppur', 'Others'],
    'Singrauli': ['Singrauli', 'Waidhan', 'Others'],
    'Pali': ['Pali', 'Others'],
  },
  'Maharashtra': {
    'Mumbai City': ['Fort', 'Colaba', 'Dadar', 'Byculla', 'Kurla', 'Andheri', 'Bandra', 'Lower Parel', 'Worli', 'Chembur', 'Govandi', 'Mankhurd', 'Others'],
    'Mumbai Suburban': ['Andheri', 'Borivali', 'Kandivali', 'Malad', 'Goregaon', 'Jogeshwari', 'Ghatkopar', 'Mulund', 'Bhandup', 'Vikhroli', 'Powai', 'Others'],
    'Pune': ['Pune', 'Pimpri', 'Chinchwad', 'Hadapsar', 'Kothrud', 'Shivajinagar', 'Kondhwa', 'Wakad', 'Hinjewadi', 'Viman Nagar', 'Baner', 'Aundh', 'Others'],
    'Thane': ['Thane', 'Navi Mumbai', 'Ulhasnagar', 'Kalyan', 'Dombivli', 'Bhiwandi', 'Mira Road', 'Vasai', 'Virar', 'Ambernath', 'Badlapur', 'Others'],
    'Nagpur': ['Nagpur', 'Wardha', 'Amravati', 'Achalpur', 'Chandrapur', 'Others'],
    'Nashik': ['Nashik', 'Sinnar', 'Igatpuri', 'Malegaon', 'Trimbakeshwar', 'Others'],
    'Aurangabad': ['Aurangabad', 'Jalna', 'Paithan', 'Waluj', 'Others'],
    'Solapur': ['Solapur', 'Pandharpur', 'Barshi', 'Akkalkot', 'Others'],
    'Kolhapur': ['Kolhapur', 'Ichalkaranji', 'Kagal', 'Others'],
    'Sangli': ['Sangli', 'Miraj', 'Kupwad', 'Islampur', 'Others'],
    'Ahmednagar': ['Ahmednagar', 'Kopargaon', 'Shirdi', 'Rahuri', 'Shrirampur', 'Others'],
    'Satara': ['Satara', 'Karad', 'Wai', 'Panchgani', 'Others'],
    'Jalgaon': ['Jalgaon', 'Bhusawal', 'Pachora', 'Amalner', 'Chalisgaon', 'Others'],
    'Amravati': ['Amravati', 'Achalpur', 'Daryapur', 'Morshi', 'Others'],
    'Latur': ['Latur', 'Udgir', 'Ahmedpur', 'Nilanga', 'Others'],
    'Nanded': ['Nanded', 'Mudkhed', 'Kinwat', 'Others'],
    'Chandrapur': ['Chandrapur', 'Warora', 'Ballarpur', 'Mul', 'Others'],
    'Raigad': ['Alibaug', 'Panvel', 'Uran', 'Khopoli', 'Pen', 'Others'],
    'Palghar': ['Palghar', 'Vasai-Virar', 'Nalasopara', 'Boisar', 'Dahanu', 'Others'],
    'Dhule': ['Dhule', 'Shirpur', 'Sakri', 'Others'],
    'Buldhana': ['Buldhana', 'Khamgaon', 'Malkapur', 'Chikhli', 'Others'],
    'Washim': ['Washim', 'Karanja', 'Mangrulpir', 'Others'],
    'Ratnagiri': ['Ratnagiri', 'Chiplun', 'Sangameshwar', 'Khed', 'Others'],
    'Sindhudurg': ['Sindhudurg', 'Kudal', 'Sawantwadi', 'Malvan', 'Others'],
    'Gondia': ['Gondia', 'Tirora', 'Arjuni-Morgaon', 'Others'],
    'Bhandara': ['Bhandara', 'Tumsar', 'Sakoli', 'Others'],
    'Akola': ['Akola', 'Akot', 'Murtizapur', 'Others'],
    'Osmanabad': ['Osmanabad', 'Tuljapur', 'Omerga', 'Others'],
    'Parbhani': ['Parbhani', 'Jintur', 'Gangakhed', 'Others'],
    'Hingoli': ['Hingoli', 'Sengaon', 'Basmat', 'Others'],
    'Yavatmal': ['Yavatmal', 'Wani', 'Pusad', 'Umarkhed', 'Others'],
    'Wardha': ['Wardha', 'Hinganghat', 'Arvi', 'Others'],
    'Nandurbar': ['Nandurbar', 'Shahada', 'Navapur', 'Others'],
    'Beed': ['Beed', 'Ambajogai', 'Georai', 'Others'],
    'Gadchiroli': ['Gadchiroli', 'Chamorshi', 'Others'],
  },
  'Manipur': {
    'Imphal West': ['Imphal', 'Lamphel', 'Lamlong', 'Patsoi', 'Others'],
    'Imphal East': ['Imphal', 'Porompat', 'Lilong', 'Others'],
    'Bishnupur': ['Bishnupur', 'Moirang', 'Nambol', 'Others'],
    'Thoubal': ['Thoubal', 'Wangjing', 'Kakching', 'Others'],
    'Senapati': ['Senapati', 'Mao', 'Others'],
    'Churachandpur': ['Churachandpur', 'Singhat', 'Others'],
    'Chandel': ['Chandel', 'Moreh', 'Others'],
    'Ukhrul': ['Ukhrul', 'Kamjong', 'Others'],
    'Tamenglong': ['Tamenglong', 'Nungba', 'Others'],
  },
  'Meghalaya': {
    'East Khasi Hills': ['Shillong', 'Cherrapunji', 'Mawlai', 'Nongthymmai', 'Others'],
    'West Khasi Hills': ['Nongstoin', 'Mairang', 'Others'],
    'Ri Bhoi': ['Nongpoh', 'Umiam', 'Others'],
    'East Jaintia Hills': ['Jowai', 'Khliehriat', 'Others'],
    'West Garo Hills': ['Tura', 'Phulbari', 'Others'],
    'East Garo Hills': ['Williamnagar', 'Baghmara', 'Others'],
    'South Garo Hills': ['Baghmara', 'Others'],
  },
  'Mizoram': {
    'Aizawl': ['Aizawl', 'Lengpui', 'Tanhril', 'Others'],
    'Lunglei': ['Lunglei', 'Tlabung', 'Others'],
    'Champhai': ['Champhai', 'Khawzawl', 'Others'],
    'Serchhip': ['Serchhip', 'N Vanlaiphai', 'Others'],
    'Kolasib': ['Kolasib', 'Bilkhawthlir', 'Others'],
  },
  'Nagaland': {
    'Kohima': ['Kohima', 'Chumukedima', 'Pherima', 'Others'],
    'Dimapur': ['Dimapur', 'Chümoukedima', 'Nagarjan', 'Others'],
    'Mokokchung': ['Mokokchung', 'Mangkolemba', 'Others'],
    'Wokha': ['Wokha', 'Bhandari', 'Others'],
    'Tuensang': ['Tuensang', 'Shamator', 'Others'],
    'Mon': ['Mon', 'Tizit', 'Others'],
    'Zunheboto': ['Zunheboto', 'Akuluto', 'Others'],
    'Phek': ['Phek', 'Pfutsero', 'Others'],
  },
  'Odisha': {
    'Khordha': ['Bhubaneswar', 'Puri Road', 'Khordha', 'Jatni', 'Balugaon', 'Others'],
    'Cuttack': ['Cuttack', 'Choudwar', 'Kendrapara', 'Athagarh', 'Others'],
    'Ganjam': ['Berhampur', 'Brahmapur', 'Gopalpur', 'Chatrapur', 'Aska', 'Others'],
    'Puri': ['Puri', 'Nimapara', 'Pipili', 'Others'],
    'Balasore': ['Balasore', 'Bhadrak', 'Soro', 'Others'],
    'Sambalpur': ['Sambalpur', 'Jharsuguda', 'Bargarh', 'Others'],
    'Sundargarh': ['Sundargarh', 'Rourkela', 'Rajgangpur', 'Bondamunda', 'Others'],
    'Koraput': ['Koraput', 'Jeypore', 'Sunabeda', 'Others'],
    'Kalahandi': ['Bhawanipatna', 'Junagarh', 'Dharmagarh', 'Others'],
    'Mayurbhanj': ['Baripada', 'Rairangpur', 'Udala', 'Others'],
    'Angul': ['Angul', 'Talcher', 'Dhenkanal', 'Others'],
    'Rayagada': ['Rayagada', 'Gunupur', 'Rayagada Town', 'Others'],
    'Bargarh': ['Bargarh', 'Padmapur', 'Sonepur', 'Others'],
    'Jajpur': ['Jajpur', 'Vyasanagar', 'Dharmasala', 'Others'],
    'Kendrapara': ['Kendrapara', 'Pattamundai', 'Marshaghai', 'Others'],
    'Dhenkanal': ['Dhenkanal', 'Kamakhyanagar', 'Hindol', 'Others'],
    'Nayagarh': ['Nayagarh', 'Odagaon', 'Khandapara', 'Others'],
    'Bolangir': ['Bolangir', 'Titlagarh', 'Kantabanji', 'Others'],
    'Malkangiri': ['Malkangiri', 'Kalimela', 'Others'],
    'Nabarangpur': ['Nabarangpur', 'Umerkote', 'Others'],
    'Kandhamal': ['Phulbani', 'Baliguda', 'Others'],
    'Baudh': ['Baudh', 'Phulbani', 'Others'],
    'Nuapada': ['Nuapada', 'Khariar', 'Others'],
    'Subarnapur': ['Sonepur', 'Binka', 'Others'],
    'Jharsuguda': ['Jharsuguda', 'Brajarajnagar', 'Others'],
    'Debagarh': ['Debagarh', 'Others'],
    'Keonjhar': ['Keonjhar', 'Barbil', 'Anandapur', 'Others'],
    'Kendujhar': ['Keonjhar', 'Joda', 'Others'],
  },
  'Punjab': {
    'Ludhiana': ['Ludhiana', 'Khanna', 'Doraha', 'Jagraon', 'Samrala', 'Others'],
    'Amritsar': ['Amritsar', 'Batala', 'Tarn Taran', 'Jandiala', 'Others'],
    'Jalandhar': ['Jalandhar', 'Phagwara', 'Nakodar', 'Kartarpur', 'Others'],
    'Patiala': ['Patiala', 'Rajpura', 'Nabha', 'Sangrur', 'Others'],
    'SAS Nagar': ['Mohali', 'Kharar', 'Zirakpur', 'Derabassi', 'Dera Bassi', 'Others'],
    'Ferozepur': ['Ferozepur', 'Abohar', 'Fazilka', 'Jalalabad', 'Others'],
    'Bathinda': ['Bathinda', 'Rampura Phul', 'Mansa', 'Others'],
    'Hoshiarpur': ['Hoshiarpur', 'Dasuya', 'Mukerian', 'Garh Shankar', 'Others'],
    'Gurdaspur': ['Gurdaspur', 'Pathankot', 'Dhariwal', 'Batala', 'Others'],
    'Rupnagar': ['Rupnagar', 'Morinda', 'Anandpur Sahib', 'Nangal', 'Others'],
    'Sangrur': ['Sangrur', 'Barnala', 'Sunam', 'Malerkotla', 'Others'],
    'Fatehgarh Sahib': ['Fatehgarh Sahib', 'Amloh', 'Mandi Gobindgarh', 'Bassi Pathana', 'Others'],
    'Moga': ['Moga', 'Baghapurana', 'Nihal Singh Wala', 'Others'],
    'Muktsar': ['Muktsar', 'Malout', 'Gidderbaha', 'Others'],
    'Nawanshahr': ['Nawanshahr', 'Banga', 'Rahon', 'Others'],
    'Kapurthala': ['Kapurthala', 'Phagwara', 'Sultanpur Lodhi', 'Kartarpur', 'Others'],
    'Faridkot': ['Faridkot', 'Kotkapura', 'Jaitu', 'Others'],
    'Tarn Taran': ['Tarn Taran', 'Patti', 'Khem Karan', 'Others'],
    'Barnala': ['Barnala', 'Tapa', 'Bhadaur', 'Others'],
    'Mansa': ['Mansa', 'Budhlada', 'Sardulgarh', 'Others'],
    'Pathankot': ['Pathankot', 'Dhar Kalan', 'Sujanpur', 'Others'],
  },
  'Rajasthan': {
    'Jaipur': ['Jaipur', 'Sanganer', 'Amer', 'Chomu', 'Kotputli', 'Shahpura', 'Bassi', 'Phagi', 'Bagru', 'Chaksu', 'Others'],
    'Jodhpur': ['Jodhpur', 'Pali', 'Sojat', 'Balotra', 'Osian', 'Mandore', 'Luni', 'Others'],
    'Udaipur': ['Udaipur', 'Rajsamand', 'Nathdwara', 'Dungarpur', 'Banswara', 'Salumber', 'Others'],
    'Kota': ['Kota', 'Bundi', 'Baran', 'Jhalawar', 'Ramganj Mandi', 'Itawa', 'Others'],
    'Ajmer': ['Ajmer', 'Pushkar', 'Kishangarh', 'Beawar', 'Nasirabad', 'Masuda', 'Others'],
    'Bikaner': ['Bikaner', 'Sri Ganganagar', 'Hanumangarh', 'Suratgarh', 'Lunkaransar', 'Others'],
    'Alwar': ['Alwar', 'Bhiwadi', 'Neemrana', 'Rajgarh', 'Behror', 'Lachhmangarh', 'Ramgarh', 'Others'],
    'Bharatpur': ['Bharatpur', 'Deeg', 'Weir', 'Bayana', 'Nagar', 'Others'],
    'Sikar': ['Sikar', 'Fatehpur', 'Lachhmangarh', 'Neem Ka Thana', 'Srimadhopur', 'Others'],
    'Nagaur': ['Nagaur', 'Merta City', 'Ladnun', 'Makrana', 'Kuchaman', 'Mundwa', 'Others'],
    'Tonk': ['Tonk', 'Malpura', 'Uniara', 'Newai', 'Others'],
    'Churu': ['Churu', 'Sardar Shahar', 'Ratangarh', 'Sujangarh', 'Rajgarh', 'Others'],
    'Jhunjhunu': ['Jhunjhunu', 'Pilani', 'Chirawa', 'Mandawa', 'Nawalgarh', 'Others'],
    'Dausa': ['Dausa', 'Lalsot', 'Bandikui', 'Sikandra', 'Others'],
    'Sawai Madhopur': ['Sawai Madhopur', 'Gangapur City', 'Khandar', 'Others'],
    'Karauli': ['Karauli', 'Hindaun City', 'Nadoti', 'Others'],
    'Dholpur': ['Dholpur', 'Bari', 'Rajakhera', 'Sarmathura', 'Others'],
    'Barmer': ['Barmer', 'Balotra', 'Sheo', 'Siwana', 'Pachpadra', 'Others'],
    'Jaisalmer': ['Jaisalmer', 'Sam', 'Pokaran', 'Nachna', 'Others'],
    'Sirohi': ['Sirohi', 'Abu Road', 'Mount Abu', 'Pindwara', 'Sheoganj', 'Others'],
    'Bhilwara': ['Bhilwara', 'Gulabpura', 'Mandalgarh', 'Shahpura', 'Mandal', 'Others'],
    'Chittorgarh': ['Chittorgarh', 'Nimach', 'Mandsaur', 'Kapasan', 'Rawatbhata', 'Others'],
    'Pratapgarh': ['Pratapgarh', 'Chhoti Sadri', 'Manpur', 'Arnod', 'Others'],
    'Bundi': ['Bundi', 'Hindoli', 'Lakheri', 'Nainwa', 'Others'],
    'Rajsamand': ['Rajsamand', 'Nathdwara', 'Kankroli', 'Railmagra', 'Others'],
    'Pali': ['Pali', 'Marwar Junction', 'Rani', 'Bali', 'Sumerpur', 'Others'],
    'Banswara': ['Banswara', 'Ghatol', 'Bagidora', 'Kushalgarh', 'Others'],
    'Dungarpur': ['Dungarpur', 'Sagwara', 'Aspur', 'Bichhiwada', 'Others'],
    'Sri Ganganagar': ['Sri Ganganagar', 'Suratgarh', 'Padampur', 'Anupgarh', 'Raisingnagar', 'Others'],
    'Hanumangarh': ['Hanumangarh', 'Nohar', 'Bhadra', 'Tibi', 'Pilibanga', 'Others'],
    'Jhalawar': ['Jhalawar', 'Jhalrapatan', 'Khanpur', 'Dag', 'Others'],
    'Baran': ['Baran', 'Shahabad', 'Kishanganj', 'Anta', 'Others'],
    'Jalore': ['Jalore', 'Sanchore', 'Bhinmal', 'Ahore', 'Others'],
  },
  'Sikkim': {
    'East Sikkim': ['Gangtok', 'Rangpo', 'Rongli', 'Pakyong', 'Others'],
    'West Sikkim': ['Gyalshing', 'Jorethang', 'Nayabazar', 'Others'],
    'North Sikkim': ['Mangan', 'Chungthang', 'Others'],
    'South Sikkim': ['Namchi', 'Jorethang', 'Ravangla', 'Others'],
  },
  'Tamil Nadu': {
    'Chennai': ['Chennai', 'Tambaram', 'Ambattur', 'Avadi', 'Porur', 'Madipakkam', 'Sholinganallur', 'Velachery', 'Perambur', 'Tondiarpet', 'Anna Nagar', 'T Nagar', 'Adyar', 'Others'],
    'Coimbatore': ['Coimbatore', 'Tirupur', 'Pollachi', 'Mettupalayam', 'Palladam', 'Others'],
    'Madurai': ['Madurai', 'Melur', 'Usilampatti', 'Thirumangalam', 'Dindigul', 'Others'],
    'Tiruchirappalli': ['Tiruchirappalli', 'Srirangam', 'Karur', 'Musiri', 'Others'],
    'Salem': ['Salem', 'Attur', 'Mettur', 'Omalur', 'Namakkal', 'Others'],
    'Tirunelveli': ['Tirunelveli', 'Nagercoil', 'Thoothukudi', 'Palayamkottai', 'Others'],
    'Erode': ['Erode', 'Gobichettipalayam', 'Bhavani', 'Dharapuram', 'Others'],
    'Vellore': ['Vellore', 'Katpadi', 'Ambur', 'Vaniyambadi', 'Others'],
    'Thoothukudi': ['Thoothukudi', 'Kovilpatti', 'Tiruchendur', 'Others'],
    'Kancheepuram': ['Kancheepuram', 'Chengalpattu', 'Tambaram', 'Alandur', 'Others'],
    'Villupuram': ['Villupuram', 'Gingee', 'Tindivanam', 'Kallakurichi', 'Others'],
    'Cuddalore': ['Cuddalore', 'Chidambaram', 'Panruti', 'Neyveli', 'Others'],
    'Thanjavur': ['Thanjavur', 'Kumbakonam', 'Pattukottai', 'Papanasam', 'Others'],
    'Dindigul': ['Dindigul', 'Palani', 'Natham', 'Others'],
    'Krishnagiri': ['Krishnagiri', 'Hosur', 'Denkanikottai', 'Bargur', 'Others'],
    'Namakkal': ['Namakkal', 'Tiruchengode', 'Rasipuram', 'Kumarapalayam', 'Others'],
    'Theni': ['Theni', 'Uthamapalayam', 'Periyakulam', 'Bodinayakkanur', 'Others'],
    'Virudhunagar': ['Virudhunagar', 'Sivakasi', 'Sattur', 'Aruppukkottai', 'Others'],
    'Ramanathapuram': ['Ramanathapuram', 'Rameswaram', 'Paramakudi', 'Kilakkarai', 'Others'],
    'Tiruvannamalai': ['Tiruvannamalai', 'Arani', 'Polur', 'Cheyyar', 'Others'],
    'Dharmapuri': ['Dharmapuri', 'Harur', 'Pennagaram', 'Others'],
    'Pudukkottai': ['Pudukkottai', 'Karaikudi', 'Aranthangi', 'Others'],
    'Nagapattinam': ['Nagapattinam', 'Mayiladuthurai', 'Sirkazhi', 'Others'],
    'Sivaganga': ['Sivaganga', 'Karaikudi', 'Devakottai', 'Others'],
    'Tiruvarur': ['Tiruvarur', 'Nannilam', 'Papanasam', 'Others'],
    'Ariyalur': ['Ariyalur', 'Jayamkondam', 'Udayarpalayam', 'Others'],
    'Perambalur': ['Perambalur', 'Veppanthattai', 'Arumbavur', 'Others'],
    'The Nilgiris': ['Ooty', 'Coonoor', 'Kotagiri', 'Gudalur', 'Others'],
    'Kanyakumari': ['Nagercoil', 'Thuckalay', 'Padmanabhapuram', 'Others'],
    'Tiruvallur': ['Tiruvallur', 'Ponneri', 'Gummidipoondi', 'Thiruvallur', 'Others'],
    'Ranipet': ['Ranipet', 'Arcot', 'Walajapet', 'Others'],
    'Tirupathur': ['Tirupathur', 'Ambur', 'Vaniyambadi', 'Others'],
    'Chengalpattu': ['Chengalpattu', 'Maraimalai Nagar', 'Kelambakkam', 'Others'],
    'Tenkasi': ['Tenkasi', 'Courtallam', 'Sankarankoil', 'Others'],
  },
  'Telangana': {
    'Hyderabad': ['Hyderabad', 'Secunderabad', 'Kukatpally', 'Begumpet', 'Ameerpet', 'Madhapur', 'Kondapur', 'Gachibowli', 'Banjara Hills', 'Jubilee Hills', 'Himayatnagar', 'Abids', 'Others'],
    'Rangareddy': ['Rangareddy', 'LB Nagar', 'Vanasthalipuram', 'Hayathnagar', 'Saroornagar', 'Shamshabad', 'Rajendra Nagar', 'Others'],
    'Medchal-Malkajgiri': ['Medchal', 'Kompally', 'Alwal', 'Quthbullapur', 'Dundigal', 'Pocharam', 'Others'],
    'Sangareddy': ['Sangareddy', 'Patancheru', 'Ameenpur', 'Zaheerabad', 'Others'],
    'Warangal Urban': ['Warangal', 'Hanamkonda', 'Kazipet', 'Matwada', 'Others'],
    'Karimnagar': ['Karimnagar', 'Jagtial', 'Mancherial', 'Ramagundam', 'Others'],
    'Nizamabad': ['Nizamabad', 'Kamareddy', 'Bodhan', 'Armoor', 'Others'],
    'Khammam': ['Khammam', 'Kothagudem', 'Palwancha', 'Others'],
    'Nalgonda': ['Nalgonda', 'Miryalaguda', 'Suryapet', 'Bhongir', 'Others'],
    'Mahbubnagar': ['Mahbubnagar', 'Wanaparthy', 'Gadwal', 'Jadcherla', 'Others'],
    'Adilabad': ['Adilabad', 'Nirmal', 'Mancherial', 'Utnoor', 'Others'],
    'Siddipet': ['Siddipet', 'Gajwel', 'Dubbak', 'Others'],
    'Medak': ['Medak', 'Toopran', 'Narayankhed', 'Others'],
    'Yadadri Bhuvanagiri': ['Yadagirigutta', 'Bhongir', 'Alair', 'Others'],
    'Suryapet': ['Suryapet', 'Huzurnagar', 'Kodad', 'Others'],
    'Nagarkurnool': ['Nagarkurnool', 'Kollapur', 'Kalwakurthy', 'Others'],
    'Vikarabad': ['Vikarabad', 'Tandur', 'Parigi', 'Others'],
    'Peddapalli': ['Ramagundam', 'Peddapalli', 'Manthani', 'Others'],
    'Rajanna Sircilla': ['Sircilla', 'Vemulawada', 'Husnabad', 'Others'],
    'Jagtial': ['Jagtial', 'Koratla', 'Others'],
    'Mancherial': ['Mancherial', 'Bellampalle', 'Chennur', 'Others'],
    'Nirmal': ['Nirmal', 'Bhainsa', 'Dilawarpur', 'Others'],
    'Kamareddy': ['Kamareddy', 'Banswada', 'Others'],
    'Wanaparthy': ['Wanaparthy', 'Gopalpet', 'Pebbair', 'Others'],
    'Mahabubabad': ['Mahabubabad', 'Dornakal', 'Others'],
    'Bhadradri Kothagudem': ['Kothagudem', 'Bhadrachalam', 'Palwancha', 'Others'],
    'Mulugu': ['Mulugu', 'Eturunagaram', 'Others'],
    'Narayanpet': ['Narayanpet', 'Makthal', 'Others'],
    'Jogulamba Gadwal': ['Gadwal', 'Aiza', 'Alampur', 'Others'],
    'Kumuram Bheem': ['Asifabad', 'Jainoor', 'Others'],
  },
  'Tripura': {
    'West Tripura': ['Agartala', 'Badharghat', 'Majlishpur', 'Sabroom', 'Others'],
    'Sepahijala': ['Bishalgarh', 'Sonamura', 'Boxanagar', 'Others'],
    'South Tripura': ['Belonia', 'Sabroom', 'Others'],
    'North Tripura': ['Dharmanagar', 'Kanchanpur', 'Panisagar', 'Others'],
    'Gomati': ['Udaipur', 'Amarpur', 'Others'],
    'Khowai': ['Khowai', 'Teliamura', 'Others'],
    'Unokoti': ['Kailashahar', 'Kumarghat', 'Others'],
    'Dhalai': ['Ambassa', 'Kamalpur', 'Others'],
  },
  'Uttar Pradesh': {
    'Lucknow': ['Lucknow', 'Aliganj', 'Gomtinagar', 'Hazratganj', 'Indira Nagar', 'Alambagh', 'Charbagh', 'Sitapur Road', 'Others'],
    'Kanpur Nagar': ['Kanpur', 'Armapur', 'Kidwai Nagar', 'Govindnagar', 'Panki', 'Others'],
    'Agra': ['Agra', 'Firozabad', 'Mathura', 'Etah', 'Ferozabad', 'Others'],
    'Varanasi': ['Varanasi', 'Jaunpur', 'Ghazipur', 'Sarnath', 'Others'],
    'Meerut': ['Meerut', 'Hapur', 'Modinagar', 'Meerut Cantt', 'Others'],
    'Prayagraj': ['Prayagraj', 'Naini', 'Phulpur', 'Shankargarh', 'Others'],
    'Ghaziabad': ['Ghaziabad', 'Noida', 'Greater Noida', 'Indirapuram', 'Vasundhara', 'Kaushambi', 'Raj Nagar Extension', 'Others'],
    'Gautam Buddha Nagar': ['Noida', 'Greater Noida', 'Dadri', 'Jewar', 'Others'],
    'Bareilly': ['Bareilly', 'Rampur', 'Badaun', 'Pilibhit', 'Others'],
    'Moradabad': ['Moradabad', 'Amroha', 'Sambhal', 'Others'],
    'Aligarh': ['Aligarh', 'Hathras', 'Kasganj', 'Atrauli', 'Others'],
    'Gorakhpur': ['Gorakhpur', 'Deoria', 'Kushinagar', 'Basti', 'Others'],
    'Faizabad': ['Faizabad', 'Ayodhya', 'Akbarpur', 'Others'],
    'Muzaffarnagar': ['Muzaffarnagar', 'Shamli', 'Kairana', 'Others'],
    'Saharanpur': ['Saharanpur', 'Deoband', 'Gangoh', 'Others'],
    'Mathura': ['Mathura', 'Vrindavan', 'Govardhan', 'Barsana', 'Others'],
    'Bulandshahr': ['Bulandshahr', 'Khurja', 'Sikandrabad', 'Others'],
    'Azamgarh': ['Azamgarh', 'Mau', 'Ballia', 'Ghosi', 'Others'],
    'Jhansi': ['Jhansi', 'Lalitpur', 'Datia', 'Orai', 'Others'],
    'Sitapur': ['Sitapur', 'Lakhimpur', 'Bahraich', 'Misrikh', 'Others'],
    'Sultanpur': ['Sultanpur', 'Amethi', 'Gauriganj', 'Others'],
    'Unnao': ['Unnao', 'Purwa', 'Bangarmau', 'Others'],
    'Hardoi': ['Hardoi', 'Sandila', 'Shahabad', 'Others'],
    'Rae Bareli': ['Rae Bareli', 'Salon', 'Unchahar', 'Others'],
    'Gonda': ['Gonda', 'Balrampur', 'Mankapur', 'Others'],
    'Barabanki': ['Barabanki', 'Fatehpur', 'Ramsanehi Ghat', 'Others'],
    'Pratapgarh': ['Pratapgarh', 'Kunda', 'Lalganj', 'Others'],
    'Kushinagar': ['Padrauna', 'Kushinagar', 'Hata', 'Others'],
    'Mirzapur': ['Mirzapur', 'Vindhyachal', 'Chunar', 'Others'],
    'Basti': ['Basti', 'Nawabganj', 'Khalilabad', 'Others'],
    'Pilibhit': ['Pilibhit', 'Puranpur', 'Bisalpur', 'Others'],
    'Lakhimpur Kheri': ['Lakhimpur', 'Gola Gokarannath', 'Nighasan', 'Others'],
    'Shahjahanpur': ['Shahjahanpur', 'Tilhar', 'Jalalabad', 'Others'],
    'Banda': ['Banda', 'Chitrakoot', 'Atarra', 'Others'],
    'Kannauj': ['Kannauj', 'Tirwa', 'Others'],
    'Farrukhabad': ['Fatehgarh', 'Farrukhabad', 'Shamsabad', 'Others'],
    'Etawah': ['Etawah', 'Mainpuri', 'Bharthana', 'Others'],
    'Budaun': ['Budaun', 'Ujhani', 'Bisauli', 'Others'],
    'Amroha': ['Amroha', 'Hasanpur', 'Dhanaura', 'Others'],
    'Shamli': ['Shamli', 'Kairana', 'Thanabhawan', 'Others'],
    'Hapur': ['Hapur', 'Garhmukteshwar', 'Pilkhuwa', 'Others'],
    'Bijnor': ['Bijnor', 'Najibabad', 'Nagina', 'Chandpur', 'Others'],
    'Muzaffarnagar (Rural)': ['Khatauli', 'Budhana', 'Jansath', 'Others'],
    'Rampur': ['Rampur', 'Bilaspur', 'Milak', 'Others'],
    'Baghpat': ['Baghpat', 'Baraut', 'Khekra', 'Others'],
    'Auraiya': ['Auraiya', 'Dibiyapur', 'Others'],
    'Hamirpur': ['Hamirpur', 'Rath', 'Maudaha', 'Others'],
    'Mahoba': ['Mahoba', 'Charkhari', 'Kabrai', 'Others'],
    'Jalaun': ['Orai', 'Konch', 'Kalpi', 'Others'],
  },
  'Uttarakhand': {
    'Dehradun': ['Dehradun', 'Rishikesh', 'Doiwala', 'Selaqui', 'Vikasnagar', 'Others'],
    'Haridwar': ['Haridwar', 'Roorkee', 'Laksar', 'Manglaur', 'Others'],
    'Nainital': ['Nainital', 'Haldwani', 'Bhowali', 'Ramnagar', 'Others'],
    'Udham Singh Nagar': ['Rudrapur', 'Kashipur', 'Jaspur', 'Sitarganj', 'Kichha', 'Others'],
    'Almora': ['Almora', 'Ranikhet', 'Jageshwar', 'Others'],
    'Tehri Garhwal': ['Tehri', 'Rishikesh', 'Narendra Nagar', 'Chamba', 'Others'],
    'Pauri Garhwal': ['Pauri', 'Kotdwar', 'Srinagar', 'Lansdowne', 'Others'],
    'Champawat': ['Champawat', 'Tanakpur', 'Lohaghat', 'Others'],
    'Bageshwar': ['Bageshwar', 'Kanda', 'Kapkot', 'Others'],
    'Chamoli': ['Chamoli', 'Gopeshwar', 'Karnaprayag', 'Others'],
    'Pithoragarh': ['Pithoragarh', 'Dharchula', 'Munsiari', 'Others'],
    'Uttarkashi': ['Uttarkashi', 'Bhatwari', 'Gangotri', 'Others'],
    'Rudraprayag': ['Rudraprayag', 'Agastyamuni', 'Kedarnath', 'Others'],
  },
  'West Bengal': {
    'Kolkata': ['Kolkata', 'Salt Lake', 'Rajarhat', 'Dum Dum', 'Behala', 'Jadavpur', 'Ballygunge', 'Park Street', 'Alipore', 'Howrah', 'Others'],
    'Howrah': ['Howrah', 'Shibpur', 'Domjur', 'Uluberia', 'Bagnan', 'Others'],
    'Hooghly': ['Chinsurah', 'Serampore', 'Chandannagar', 'Arambagh', 'Mankundu', 'Others'],
    'North 24 Parganas': ['Barrackpore', 'Barasat', 'Naihati', 'Kalyani', 'Madhyamgram', 'Birati', 'Habra', 'Others'],
    'South 24 Parganas': ['Alipore', 'Baruipur', 'Diamond Harbour', 'Sonarpur', 'Budge Budge', 'Others'],
    'Purba Medinipur': ['Tamluk', 'Haldia', 'Contai', 'Digha', 'Mecheda', 'Others'],
    'Paschim Medinipur': ['Midnapore', 'Kharagpur', 'Ghatal', 'Jhargram', 'Others'],
    'Bardhaman': ['Bardhaman', 'Durgapur', 'Asansol', 'Ranigunj', 'Kalna', 'Others'],
    'Murshidabad': ['Berhampore', 'Jangipur', 'Domkal', 'Jiaganj', 'Sagardighi', 'Others'],
    'Nadia': ['Kalyani', 'Krishnanagar', 'Ranaghat', 'Chakdaha', 'Nabadwip', 'Others'],
    'Birbhum': ['Suri', 'Bolpur', 'Rampurhat', 'Sainthia', 'Others'],
    'Malda': ['English Bazar', 'Old Malda', 'Chanchal', 'Gazole', 'Others'],
    'North Dinajpur': ['Raiganj', 'Islampur', 'Dalkhola', 'Others'],
    'South Dinajpur': ['Balurghat', 'Gangarampur', 'Hili', 'Others'],
    'Jalpaiguri': ['Jalpaiguri', 'Siliguri', 'Mal', 'Alipurduar', 'Others'],
    'Darjeeling': ['Darjeeling', 'Siliguri', 'Kalimpong', 'Kurseong', 'Others'],
    'Alipurduar': ['Alipurduar', 'Falakata', 'Kumargram', 'Others'],
    'Cooch Behar': ['Cooch Behar', 'Dinhata', 'Mathabhanga', 'Others'],
    'Jhargram': ['Jhargram', 'Lodhasuli', 'Others'],
    'Purulia': ['Purulia', 'Jhalda', 'Raghunathpur', 'Manbazar', 'Others'],
    'Bankura': ['Bankura', 'Bishnupur', 'Sonamukhi', 'Khatra', 'Others'],
    'Paschim Bardhaman': ['Asansol', 'Durgapur', 'Ranigunj', 'Kulti', 'Others'],
  },
  // Union Territories
  'Delhi': {
    'Central Delhi': ['Connaught Place', 'Chandni Chowk', 'Karol Bagh', 'Paharganj', 'Daryaganj', 'Others'],
    'East Delhi': ['Preet Vihar', 'Mayur Vihar', 'Patparganj', 'Shahdara', 'Laxmi Nagar', 'Others'],
    'North Delhi': ['Rohini', 'Pitampura', 'Shalimar Bagh', 'Model Town', 'Bawana', 'Others'],
    'North East Delhi': ['Yamuna Vihar', 'Bhajanpura', 'Mustafabad', 'Nand Nagri', 'Others'],
    'North West Delhi': ['Dwarka', 'Janakpuri', 'Uttam Nagar', 'Paschim Vihar', 'Pitampura', 'Others'],
    'South Delhi': ['Saket', 'Greater Kailash', 'Malviya Nagar', 'Hauz Khas', 'Vasant Kunj', 'Vasant Vihar', 'Others'],
    'South East Delhi': ['Lajpat Nagar', 'Kalkaji', 'Govindpuri', 'Okhla', 'Jasola', 'Others'],
    'South West Delhi': ['Mahipalpur', 'Palam', 'Dwarka', 'Kapashera', 'Others'],
    'West Delhi': ['Rajouri Garden', 'Tilak Nagar', 'Vikaspuri', 'Kirti Nagar', 'Subhash Nagar', 'Others'],
    'New Delhi': ['New Delhi', 'Chanakyapuri', 'Sarojini Nagar', 'Lodhi Road', 'Others'],
    'Shahdara': ['Shahdara', 'Dilshad Garden', 'Vivek Vihar', 'Jhilmil', 'Others'],
    'Outer Delhi': ['Narela', 'Alipur', 'Bawana', 'Others'],
    'Outer North Delhi': ['Burari', 'Mukherjee Nagar', 'Timarpur', 'Others'],
  },
  'Andaman and Nicobar Islands': {
    'South Andaman': ['Port Blair', 'Bambooflat', 'Garacharma', 'Others'],
    'North and Middle Andaman': ['Mayabunder', 'Diglipur', 'Rangat', 'Others'],
    'Nicobars': ['Car Nicobar', 'Campbell Bay', 'Others'],
  },
  'Chandigarh': {
    'Chandigarh': ['Chandigarh', 'Sector 17', 'Sector 22', 'Sector 35', 'Manimajra', 'Industrial Area', 'Others'],
  },
  'Dadra and Nagar Haveli and Daman and Diu': {
    'Dadra and Nagar Haveli': ['Silvassa', 'Dadra', 'Khanvel', 'Others'],
    'Daman': ['Daman', 'Nani Daman', 'Moti Daman', 'Others'],
    'Diu': ['Diu', 'Fudam', 'Others'],
  },
  'Jammu and Kashmir': {
    'Jammu': ['Jammu', 'Samba', 'Udhampur', 'Others'],
    'Kathua': ['Kathua', 'Basohli', 'Billawar', 'Others'],
    'Srinagar': ['Srinagar', 'Pampore', 'Soura', 'Hyderpora', 'Others'],
    'Anantnag': ['Anantnag', 'Bijbehara', 'Pahalgam', 'Others'],
    'Baramulla': ['Baramulla', 'Sopore', 'Pattan', 'Others'],
    'Budgam': ['Budgam', 'Magam', 'Beerwah', 'Others'],
    'Pulwama': ['Pulwama', 'Pampore', 'Awantipora', 'Others'],
    'Kupwara': ['Kupwara', 'Karnah', 'Handwara', 'Others'],
    'Doda': ['Doda', 'Bhaderwah', 'Gandoh', 'Others'],
    'Rajouri': ['Rajouri', 'Nowshera', 'Kalakote', 'Others'],
    'Poonch': ['Poonch', 'Surankote', 'Mandi', 'Others'],
    'Reasi': ['Reasi', 'Arnas', 'Mahore', 'Others'],
    'Kulgam': ['Kulgam', 'Devsar', 'Others'],
    'Shopian': ['Shopian', 'Kellar', 'Others'],
    'Bandipora': ['Bandipora', 'Gurez', 'Others'],
    'Ganderbal': ['Ganderbal', 'Kangan', 'Lar', 'Others'],
    'Kishtwar': ['Kishtwar', 'Paddar', 'Drabshalla', 'Others'],
    'Ramban': ['Ramban', 'Banihal', 'Gool', 'Others'],
    'Udhampur': ['Udhampur', 'Ramnagar', 'Chenani', 'Others'],
  },
  'Ladakh': {
    'Leh': ['Leh', 'Nubra', 'Zanskar', 'Others'],
    'Kargil': ['Kargil', 'Sanku', 'Zanskar', 'Others'],
  },
  'Lakshadweep': {
    'Kavaratti': ['Kavaratti', 'Others'],
    'Agatti': ['Agatti', 'Others'],
    'Amini': ['Amini', 'Others'],
    'Androth': ['Androth', 'Others'],
    'Minicoy': ['Minicoy', 'Others'],
  },
  'Puducherry': {
    'Puducherry': ['Puducherry', 'Oulgaret', 'Villianur', 'Ariyankuppam', 'Others'],
    'Karaikal': ['Karaikal', 'Nedungadu', 'Others'],
    'Mahe': ['Mahe', 'Chaliyam', 'Others'],
    'Yanam': ['Yanam', 'Others'],
  },
};

export const INDIA_STATES = Object.keys(INDIA_LOCATIONS).sort();

export function getDistricts(state: string): string[] {
  if (!state || !INDIA_LOCATIONS[state]) return [];
  return Object.keys(INDIA_LOCATIONS[state]).sort();
}

export function getCities(state: string, district: string): string[] {
  if (!state || !district || !INDIA_LOCATIONS[state]?.[district]) return [];
  const cities = INDIA_LOCATIONS[state][district];
  // Ensure "Others" is always last
  const withoutOthers = cities.filter(c => c !== 'Others');
  return [...withoutOthers.sort(), 'Others'];
}
