export const LOAN_PRODUCTS = [
  {
    key: 'personal',
    title: 'Personal Loan',
    rate: '10.50% p.a.',
    maxAmount: 'Up to ₹50 L',
    icon: 'Wallet',
    highlight: true,
    badge: 'Our Core Product',
    description: 'Instant personal loans with minimal documentation. Salaried & self-employed. Zero collateral required.',
    features: ['No collateral', 'Quick disbursal', 'Flexible tenure', 'Part-prepayment free'],
  },
  {
    key: 'education',
    title: 'Education Loan',
    rate: '9.50% p.a.',
    maxAmount: 'Up to ₹1.5 Cr',
    icon: 'GraduationCap',
    highlight: false,
    badge: 'via Saral Vidya',
    description: 'Finance your education at top institutions in India & abroad — exclusively powered by Poonawala Fincorp.',
    features: ['Study in India & abroad', 'Poonawala Fincorp rates', 'Covers fees & living', 'Moratorium period'],
    partner: 'Saral Vidya',
    partnerUrl: 'https://saralvidya.in',
    partnerNote: 'Exclusively via Poonawala Fincorp',
  },
  {
    key: 'business',
    title: 'Business Loan',
    rate: '14.00% p.a.',
    maxAmount: 'Up to ₹5 Cr',
    icon: 'Briefcase',
    highlight: false,
    badge: 'via Real Finserv',
    description: 'Fuel your business growth with flexible working capital — exclusively powered by Real Finserv.',
    features: ['Working capital', 'Term loans', 'OD facility', 'Business expansion'],
    partner: 'Real Finserv',
    partnerNote: 'Exclusively via Real Finserv',
  },
];

export const PARTNERS = [
  {
    id: 'saral-vidya',
    brand: 'Saral Vidya',
    tagline: 'Education Loans Made Simple',
    url: 'https://saralvidya.in',
    domain: 'saralvidya.in',
    lender: 'Poonawala Fincorp',
    lenderNote: 'Exclusive banking partner',
    product: 'Education Loans',
    highlight: 'Up to ₹1.5 Cr',
    rate: 'From 9.50% p.a.',
    color: '#1a3a5c',
    accentColor: '#3B82F6',
    description: 'Saral Vidya is our dedicated education loan brand — helping students fund their dreams at top institutions in India and abroad, backed exclusively by Poonawala Fincorp.',
    features: [
      'Courses in India & overseas',
      'Up to ₹1.5 Cr loan amount',
      'Moratorium till course completion',
      'Covers tuition, living & travel expenses',
    ],
  },
  {
    id: 'real-finserv',
    brand: 'Real Finserv',
    tagline: 'Business Loans. Real Fast.',
    url: null,
    domain: null,
    lender: 'Real Finserv',
    lenderNote: 'Our business lending arm',
    product: 'Business Loans',
    highlight: 'Up to ₹5 Cr',
    rate: 'From 14.00% p.a.',
    color: '#0A1F44',
    accentColor: '#D4AF37',
    description: 'Real Finserv is our exclusive business lending partner — providing working capital, term loans, and OD facilities to fuel business growth across India.',
    features: [
      'Working capital & term loans',
      'Up to ₹5 Cr sanction',
      'Minimal documentation',
      'Decision in 48 hours',
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: 'Amit Verma',
    city: 'Delhi',
    product: 'Personal Loan',
    amount: '₹15 L',
    lender: 'Best Offer Matched',
    days: '2 days',
    review: 'Got my personal loan at 10.9% — much better than what my bank offered directly. The advisor handled everything end-to-end. Couldn\'t have been easier.',
    rating: 5,
  },
  {
    name: 'Priya Sharma',
    city: 'Mumbai',
    product: 'Personal Loan',
    amount: '₹8 L',
    lender: 'Best Rate Secured',
    days: '36 hours',
    review: 'Needed urgent funds for a family emergency. Real Money disbursed my personal loan in just 36 hours — absolutely incredible speed and service.',
    rating: 5,
  },
  {
    name: 'Rahul Gupta',
    city: 'Jaipur',
    product: 'Personal Loan',
    amount: '₹20 L',
    lender: 'Top Offer Selected',
    days: '3 days',
    review: 'I was confused by different lender offers. The advisor from Real Money simplified everything and helped me pick the best deal. Highly professional.',
    rating: 5,
  },
  {
    name: 'Anita Iyer',
    city: 'Bengaluru',
    product: 'Education Loan',
    amount: '₹40 L',
    lender: 'Poonawala Fincorp',
    days: '7 days',
    review: 'Saral Vidya secured my education loan from Poonawala Fincorp for my MBA abroad. The team handled all documentation professionally. Dream come true!',
    rating: 5,
  },
  {
    name: 'Karan Mehta',
    city: 'Pune',
    product: 'Business Loan',
    amount: '₹35 L',
    lender: 'Real Finserv',
    days: '4 days',
    review: 'Real Finserv approved my business loan in 4 days. The working capital helped me expand my retail chain. Zero hidden charges, complete transparency.',
    rating: 5,
  },
  {
    name: 'Sunita Patel',
    city: 'Ahmedabad',
    product: 'Personal Loan',
    amount: '₹12 L',
    lender: 'Best Rate Matched',
    days: '48 hours',
    review: 'Took a personal loan for home renovation. Real Money matched me with the best rate available. Process was 100% digital and stress-free.',
    rating: 5,
  },
];

export const FAQ_ITEMS = [
  {
    key: '1',
    label: 'What is Real Money?',
    children: 'Real Money is a Corporate Direct Selling Agent (DSA) headquartered in Jaipur, Rajasthan, with over 22 years of experience in the lending industry. We are empanelled with leading banks and NBFCs across India — including HDFC Bank, ICICI Bank, Axis Bank, Kotak Mahindra Bank, Bajaj Finance, Tata Capital, Piramal Finance, Poonawala Fincorp, and 40+ other lenders. We specialize in Personal Loans and help borrowers get access to the best rates and fastest approvals by leveraging our deep relationships with these lending institutions.',
  },
  {
    key: '2',
    label: 'Is Real Money a registered DSA?',
    children: 'Yes. Real Money is a legally incorporated Private Limited Company registered under the Companies Act, 2013. We operate as a Corporate DSA (Direct Selling Agent) authorized by our lender partners — comprising major banks and NBFCs regulated by the Reserve Bank of India. All our operations are conducted in compliance with applicable RBI guidelines and the Fair Practice Code.',
  },
  {
    key: '3',
    label: 'Do you charge any fees from customers?',
    children: 'No — our advisory services are completely free for borrowers. We are compensated by lender partners on successful loan disbursals. We follow a Fair Practice Code and maintain full transparency: if any processing fee or documentation charge is applicable, it is always disclosed upfront before you proceed. We never charge hidden fees.',
  },
  {
    key: '4',
    label: 'What is Saral Vidya and how does it work?',
    children: 'Saral Vidya (saralvidya.in) is our dedicated education loan brand. We have an exclusive partnership with Poonawala Fincorp to provide education loans up to ₹1.5 Cr for courses in India and abroad. Saral Vidya handles the entire journey from application to disbursal — you only deal with us, and the loan is sourced exclusively from Poonawala Fincorp at competitive rates.',
  },
  {
    key: '5',
    label: 'What is Real Finserv and what loans does it offer?',
    children: 'Real Finserv is our exclusive business lending partner. It offers business loans including working capital, term loans, and OD facilities up to ₹5 Cr. If you need a business loan, Real Finserv is your single-window solution — fast approval, minimal documentation, and transparent pricing. No other business lender is involved.',
  },
  {
    key: '6',
    label: 'How long does personal loan approval take?',
    children: 'For personal loans with complete documentation, approval can happen in 24–48 hours. Our average disbursal time is under 48 hours once documentation is complete. We actively follow up with lender partners on your behalf to ensure the fastest possible processing.',
  },
  {
    key: '7',
    label: 'What documents are required for a personal loan?',
    children: 'Personal loan documentation is minimal: (1) KYC — Aadhaar and PAN card; (2) Income proof — salary slips (last 3 months) for salaried, or ITR + bank statements for self-employed; (3) Bank statements — last 6 months. Our advisors will provide you a precise checklist based on your specific requirement and lender.',
  },
  {
    key: '8',
    label: 'How is my personal & financial data protected?',
    children: 'We take data privacy seriously. Your personal and financial data is encrypted end-to-end and stored on secure servers. We share your information only with the specific lender you explicitly consent to apply with. You can request deletion of your data at any time by writing to contact@realmoneygroups.in.',
  },
];

export const STATS = [
  { label: 'Years in the Industry', value: 22, suffix: '+', prefix: '' },
  { label: 'Personal Loans Disbursed', value: 7500, suffix: '+', prefix: '' },
  { label: 'Customer Rating', value: 4.8, suffix: '/5', prefix: '' },
  { label: 'Advisory Fee', value: 0, suffix: '', prefix: '₹' },
];
