ALTER TABLE conversations ALTER COLUMN connector_id DROP NOT NULL;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS rm_id UUID;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS conversation_type VARCHAR(50) NOT NULL DEFAULT 'EXTERNAL_CONNECTOR_OPS';
